services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple-bank
    container_name: simplebank-db
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV_DATABASE_SOURCE=postgres://root:secret@simplebank-db:5432/simple-bank?sslmode=disable
      - ENV_TOKEN_KEY=2bddd92e3cbe124f65091c39bdad5bf5
    container_name: simplebank-server
    depends_on:
      - db
    command: ["/app/main"]